/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en' | 'ar') | ('ru' | 'en' | 'ar')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'ru' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  pageKey: 'home' | 'solutions' | 'pricing' | 'get-proposal' | 'concepts' | 'for-startups' | 'for-partners' | 'method';
  /**
   * Human-readable page name for editors.
   */
  internalName: string;
  metaTitle?: string | null;
  metaDescription?: string | null;
  layout: (
    | {
        eyebrow?: string | null;
        /**
         * Fallback title. Used if titleRows are not filled. You can keep it for quick editing, but titleRows give a closer match to the original hero styling.
         */
        title?: string | null;
        /**
         * Recommended for pixel-closer hero styling. Each row can contain several segments with different tone.
         */
        titleRows?:
          | {
              segments: {
                text: string;
                tone?: ('default' | 'emphasis' | 'muted') | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[]
          | null;
        description?: string | null;
        /**
         * Optional small supporting note under the main description.
         */
        supportingNote?: string | null;
        tags?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        primaryButtonLabel?: string | null;
        primaryPageKey?:
          | (
              | 'home'
              | 'solutions'
              | 'pricing'
              | 'get-proposal'
              | 'concepts'
              | 'for-startups'
              | 'for-partners'
              | 'method'
            )
          | null;
        secondaryButtonLabel?: string | null;
        secondaryPageKey?:
          | (
              | 'home'
              | 'solutions'
              | 'pricing'
              | 'get-proposal'
              | 'concepts'
              | 'for-startups'
              | 'for-partners'
              | 'method'
            )
          | null;
        desktopBadgeLabel?: string | null;
        mobileBadgeLabel?: string | null;
        desktopImage?: (number | null) | Media;
        mobileImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow: string;
        title: string;
        /**
         * Optional supporting paragraph under the title. Used in Arabic version in the original design.
         */
        description?: string | null;
        items: {
          variant: 'icon' | 'step';
          icon?: ('trendingUp' | 'trophy' | 'code') | null;
          /**
           * Small top label. For RU this is EN word (Raise/Win/Build). Optional for step cards.
           */
          kicker?: string | null;
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'valueHome';
      }
    | {
        eyebrow: string;
        title: string;
        subheadline: string;
        metaBadges: {
          label: string;
          id?: string | null;
        }[];
        videoLabel?: string | null;
        durationLabel?: string | null;
        timeline: {
          number: string;
          label: string;
          description: string;
          id?: string | null;
        }[];
        highlightsTitle: string;
        highlights: {
          label: string;
          id?: string | null;
        }[];
        ctaTitle: string;
        ctaSubtext: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoWalkthroughHome';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          icon: 'fileText' | 'users' | 'gitBranch' | 'layoutGrid' | 'palette' | 'mousePointer' | 'layers' | 'fileCheck';
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'deliverablesHome';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'whyHome';
      }
    | {
        sectionId?: string | null;
        eyebrow: string;
        title: string;
        problemLabel: string;
        solutionLabel: string;
        resultLabel: string;
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        items: {
          title: string;
          problem: string;
          solution: string;
          result: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'audienceHome';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        challengeLabel: string;
        structuredLabel: string;
        deliveredLabel: string;
        viewConceptsLabel: string;
        conceptsPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        previousAriaLabel: string;
        nextAriaLabel: string;
        items: {
          title: string;
          badge: string;
          challenge: string;
          structured: string;
          delivered: string;
          imageUrl: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'conceptsHome';
      }
    | {
        sectionId?: string | null;
        eyebrow: string;
        title: string;
        description: string;
        items: {
          number: string;
          title: string;
          description: string;
          details: {
            label: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'methodHome';
      }
    | {
        sectionId?: string | null;
        title: string;
        description: string;
        steps: {
          icon: 'fileText' | 'mail' | 'checkCircle';
          title: string;
          description: string;
          id?: string | null;
        }[];
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'proposalHome';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          title: string;
          subtitle: string;
          imageUrl: string;
          alt: string;
          id?: string | null;
        }[];
        bottomNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'samplePreviewHome';
      }
    | {
        items: {
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustHome';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqHome';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageKey?: T;
  internalName?: T;
  metaTitle?: T;
  metaDescription?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              titleRows?:
                | T
                | {
                    segments?:
                      | T
                      | {
                          text?: T;
                          tone?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              description?: T;
              supportingNote?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              desktopBadgeLabel?: T;
              mobileBadgeLabel?: T;
              desktopImage?: T;
              mobileImage?: T;
              id?: T;
              blockName?: T;
            };
        valueHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    variant?: T;
                    icon?: T;
                    kicker?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoWalkthroughHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subheadline?: T;
              metaBadges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              videoLabel?: T;
              durationLabel?: T;
              timeline?:
                | T
                | {
                    number?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              highlightsTitle?: T;
              highlights?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              ctaTitle?: T;
              ctaSubtext?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              id?: T;
              blockName?: T;
            };
        deliverablesHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        audienceHome?:
          | T
          | {
              sectionId?: T;
              eyebrow?: T;
              title?: T;
              problemLabel?: T;
              solutionLabel?: T;
              resultLabel?: T;
              ctaLabel?: T;
              ctaPageKey?: T;
              items?:
                | T
                | {
                    title?: T;
                    problem?: T;
                    solution?: T;
                    result?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        conceptsHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              challengeLabel?: T;
              structuredLabel?: T;
              deliveredLabel?: T;
              viewConceptsLabel?: T;
              conceptsPageKey?: T;
              previousAriaLabel?: T;
              nextAriaLabel?: T;
              items?:
                | T
                | {
                    title?: T;
                    badge?: T;
                    challenge?: T;
                    structured?: T;
                    delivered?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        methodHome?:
          | T
          | {
              sectionId?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    details?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        proposalHome?:
          | T
          | {
              sectionId?: T;
              title?: T;
              description?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
        samplePreviewHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    imageUrl?: T;
                    alt?: T;
                    id?: T;
                  };
              bottomNote?: T;
              id?: T;
              blockName?: T;
            };
        trustHome?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  brandTitle?: string | null;
  brandSubtitle?: string | null;
  navItems?:
    | {
        label: string;
        pageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaPageKey?:
    | ('home' | 'solutions' | 'pricing' | 'get-proposal' | 'concepts' | 'for-startups' | 'for-partners' | 'method')
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandTitle?: string | null;
  brandSubtitle?: string | null;
  description?: string | null;
  email?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              pageKey:
                | 'home'
                | 'solutions'
                | 'pricing'
                | 'get-proposal'
                | 'concepts'
                | 'for-startups'
                | 'for-partners'
                | 'method';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  brandTitle?: T;
  brandSubtitle?: T;
  navItems?:
    | T
    | {
        label?: T;
        pageKey?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaPageKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandTitle?: T;
  brandSubtitle?: T;
  description?: T;
  email?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              pageKey?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}